<a href="https://colab.research.google.com/github/devesssi/dl-playground/blob/main/D1_tensors_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia smi

/bin/bash: line 1: nvidia: command not found


In [ ]:
# the statement to import the pytorch to collab
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
#create a new tensor by copying data from an array-like
#object such as a list, tuple, or NumPy array
scalar = torch.tensor(6)
scalar
#a scalar is a 0 dimension tensor or a single no

tensor(6)

In [ ]:
scalar.ndim
#this gives the dimension of the scalar

0

In [ ]:
scalar.item()

6

In [ ]:
#A vector is a single dimension tensor but can contain many numbers
vector = torch.tensor([2,2])
vector
# the no of pair of closing sqr brackets = no of dimensions (typically) count this "["

tensor([2, 2])

In [ ]:
vector.ndim
# it has 1 dim

vector.shape


torch.Size([2])

In [ ]:
scalar.item()
#item() is a method useto retrieve the python no from the integer! for eg

6

In [ ]:
# whats the diff between shape and item specifically in usage
##-->
# shape is an attribute
# item() is a method


scalar.shape # why?

torch.Size([])

In [ ]:
#The shape tells you how the elements inside them are arranged.
vector.shape

torch.Size([2])

In [ ]:
Matrix = torch.tensor([[1,2,3,4],[1,2,4,5]])


In [ ]:
Matrix.shape
#shape gaved us the elements and the amount
# it is 2 elements deep and 4 element wide

torch.Size([2, 4])

In [ ]:
#matrix has a dim (no of sqr brackets )of 2
Matrix.ndim

2

In [ ]:
#a tensor is a more general mathematical object
# that can exist in any number of dimensions
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
# tensors can represent almost anyhting
TENSOR.ndim

3

In [ ]:
TENSOR.shape

# Each place in the size result represents a dim

"""
The torch.Size([1, 3, 3]) represents the shape of a tensor in PyTorch,
where each number in the list corresponds to the size of a specific dimension
of the tensor. In this case, the tensor has three dimensions, with the first dimension
having a size of 1, the second dimension having a size of 3, and the third dimension also having a size of 3.
This means that the tensor contains 1 "batch" of data, with each data point
being a 3x3 matrix.

one dimension of 3by3

"""

torch.Size([1, 3, 3])

**RANDOM TENSORS**

**We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

In [ ]:
""" can create a new tensor using the below function torch.rand() with the size parameter
 torch.rand( size = ()) ==>  The flexibility of torch.rand() is that we can adjust
 the size to be whatever we want.
For example, say you wanted a random tensor in the common image shape of
 [224, 224, 3] ([height, width, color_channels]).

if we don't put the size in its the default
"""
random_tensor = torch.rand(size = ( 2, 4))
random_tensor, random_tensor.dtype
# dtype will give you the datatype of the tensor, bydefault float32


(tensor([[0.8957, 0.1362, 0.6774, 0.5144],
         [0.2349, 0.6470, 0.9525, 0.0857]]),
 torch.float32)

In [ ]:
random_tensor.ndim

2

**Zeros and ones**
zeros and one's are used in for masking purposes that is suppose you've got a tensor t1 which is of shape( 1,3,3) and for some reason you dont want your model to read the data of any particular dimensions particualar row,col naively ... then you'll just create a zerotensor of that shape and multiply it by the t1 the og tensors and guess what the data you dont want your computer read will get zero(disappear) 0 x 3 = 0 ....

simarly for one if you want some data in the og form than create a tensor of that shape multiply it and save it. BOOM


In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so

In [ ]:
#here range is used which will get depreceted in the future version of torch
r1 = torch.range(0 ,10, 2)
r1

/tmp/ipython-input-47-2466555211.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  r1 = torch.range(0 ,10, 2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
# torch.arange()==> this will get used
r2 = torch.arange(2,20,0.5)
r2

tensor([ 2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,
         6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000,
        10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000, 13.0000, 13.5000,
        14.0000, 14.5000, 15.0000, 15.5000, 16.0000, 16.5000, 17.0000, 17.5000,
        18.0000, 18.5000, 19.0000, 19.5000])

In [ ]:
"""
SOMETIMES YOU MAY WANT TO CREATE A TENSOR OF CERTAIN TYPE WITH THE SAME SHAPE AS ANOTHER TENSOR
FOR 0'S AND 1'S:

"""

In [ ]:
t1 = torch.zeros_like(r2)
t1

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
t2 = torch.ones_like(r2)
t2

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Tensor datatypes**

There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

ISSUES:

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).




In [ ]:
float_16_tensor = torch.tensor([2,6,8],
                               dtype = torch.float16 )
float_16_tensor.dtype

torch.float16


**Getting information from tensors**
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)
Let's create a random tensor and find out details about it.

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

In [ ]:
# Create a tensor
randdom_ten = torch.rand(3,4)
randdom_ten

tensor([[0.4465, 0.8134, 0.8124, 0.9287],
        [0.8852, 0.3650, 0.0416, 0.5415],
        [0.1561, 0.4962, 0.2334, 0.2397]])

In [ ]:
# Find out details about it
print(f" The shape of the tensor is {randdom_ten.shape}")
print(f" The datatype of the tensor is {randdom_ten.dtype}")
print(f" The device tensor is stored on {randdom_ten.device}")



 The shape of the tensor is torch.Size([3, 4])
 The datatype of the tensor is torch.float32
 The device tensor is stored on cpu


Manipulating tensors (tensor operations)


Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [ ]:
#BASIC OPERATION
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

BUILT-IN FUNCTIONS:
PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like * instead of torch.mul()